name: "CI Build"
on : "push"
jobs:
  Build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13.7"
         
      - name: Install Packages
        run: pip install -r requirements.txt

      - name: Deploying
        run: echo "Deploying ..."